### PR TITLE
fix compiler error

### LINKED ISSUE #294: Error: write EPIPE
Error: write EPIPE
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16)
[Error - 6:43:30 PM] Connection to server got closed. Server will not be restarted.

### PR DESCRIPTION
**Pull request by babyface001**
try fix #294

### CODE REVIEW

**Comment by babyface001** [comment]
works as expected.

**Comment by kanej** [comment]
@babyface001 this is excellent, thanks. We will review it today or tomorrow.

**Comment by antico5** [comment]
Will squash-merge this. Build is failing because of the linter but I'll push a commit fixing that

**Comment by kanej** [comment]
@babyface001 thanks again for this. We will push a new version with this fix in the next couple of days and let you know here when it goes out.

**Pull request merged**
