### PR TITLE
fix: improve forge binary lookup

### LINKED ISSUE #354: Assumes Foundry installation location
The location of the `forge` executable is assumed to be `~/.foundry/bin/forge` on non-Windows. I think this is the location where `foundryup` installs, but it can also be installed by other means in other locations in the `$PATH`.

```
Error: Command failed: ~/.foundry/bin/forge config --json
/bin/sh: line 1: ~/.foundry/bin/forge: No such file or directory
```

### PR DESCRIPTION
**Pull request by antico5**
Closes #354

### CODE REVIEW

**Review by kanej — COMMENTED** [review]
This looks good.

I will do a round of tests on windows next.

**Comment by kanej** [comment]
I have tested on windows by opening foundry and causing diagnostics to appear. I removed forge from my path so that the vscode terminal couldn't find `forge`, the extension used the fallback location instead.

**Comment by kanej** [comment]
We should add the same fallback to the client for formatting. @antico5

**Comment by antico5** [comment]
@kanej fallback added to client!

**Review by kanej — APPROVED** [review]

**Pull request merged**
