### PR TITLE
Natspec completions

### LINKED ISSUE #296: Generate comments automatically for a function in solidity
Hi

I would like to suggest you support the auto-comment generation feature for solidity extension.

For example:
let's assume we have this function.

```
function setAdmin(address _admin, bool _enabled) external onlyOwner {
        _admins[_admin] = _enabled;
        
        emit SetAdminAccess(true);
    }
```
Then I want to have a comment skeleton like this when I write `/** ` and press `enter`.

```
/**
     * @notice
     *
     * @param _admin
     * @param _enabled
     */
```

I think this is possible because you are providing this for javascript/typescript already.

Looking forward to hearing from you.

Best regards,
Meanking

### LINKED ISSUE #342: Support natspec in contract/interface/library completions
Similar to #328, provide a subset of natspec auto-inserts on a `/** */` completion before a contract or library or interface.

Based on the docs: https://docs.soliditylang.org/en/latest/natspec-format.html#tags, it looks like only `@title`, `@author`, `@notice` and `@dev` are supported. Lets include `@title` and `@dev` by default leaving `@notice` and `@author` out.

### LINKED ISSUE #343: Support natspec in event/state variable/public state variable
Similar to https://github.com/NomicFoundation/hardhat-vscode/pull/328, provide a subset of natspec auto-inserts on a /** */ completion before an event, state variable or public state variable.

This should be based on the docs: https://docs.soliditylang.org/en/latest/natspec-format.html#tags. 

For events it seems to `@dev` and `@param`.

But we should investigate why public state variables have an `@return` while state variables don't.

### PR DESCRIPTION
**Pull request by antico5**
closes #342
closes #343 
closes #296

This one is branched off a rebased version of PR #328

### CODE REVIEW

**Review by kanej — COMMENTED** [review]
This is great.

I have pinged the channel to confirm people are happy with the suggestion we are making to users.

Reading through the spec I suspect we need to support completions on `///` comments as well. Does that require a different approach?

**Comment by antico5** [comment]
> This is great.
> 
> I have pinged the channel to confirm people are happy with the suggestion we are making to users.
> 
> Reading through the spec I suspect we need to support completions on `///` comments as well. Does that require a different approach?

I think we can achieve that with some small adaptation. Should I add that to this PR?

**Comment by kanej** [comment]
> > This is great.
> > I have pinged the channel to confirm people are happy with the suggestion we are making to users.
> > Reading through the spec I suspect we need to support completions on `///` comments as well. Does that require a different approach?
> 
> I think we can achieve that with some small adaptation. Should I add that to this PR?

Yes, lets add that to the requirement.

**Comment by antico5** [comment]
@kanej triple forward slash format is implemented! ready to re-review

**Comment by antico5** [comment]
@kanej ready for review!

**Review by kanej — APPROVED** [review]
I have tested and generated docs from the defaults using solc: https://docs.soliditylang.org/en/latest/natspec-format.html#documentation-output.

I am approving, but can I request one change which is that public state variables should not default to @dev, just @notice.

**Pull request merged**
